/* WARNING: Autogenerated file - see ./make-cairo-boilerplate-constructors.sh! */

#include "cairo-boilerplate-private.h"

void _cairo_boilerplate_register_all (void);

extern void _register_win32 (void);
extern void _register_win32_printing (void);
extern void _register_egl (void);
/* extern void _register_skia (void); */
extern void _register_test (void);

void
_cairo_boilerplate_register_all (void)
{
    _register_win32 ();
    _register_win32_printing ();
    _register_egl ();
    /* _register_skia (); */
    // _register_test ();
}
